./bin/boardfolding < Boards/TC0.txt
./bin/boardfolding < Boards/TC1.txt
./bin/boardfolding < Boards/TC2.txt
./bin/boardfolding < Boards/TC3.txt
./bin/boardfolding < Boards/TC4.txt
./bin/boardfolding < Boards/D001.txt
./bin/boardfolding < Boards/D002.txt
./bin/boardfolding < Boards/D003.txt
./bin/boardfolding < Boards/D004.txt
./bin/boardfolding < Boards/D005.txt
./bin/boardfolding < Boards/D006.txt
./bin/boardfolding < Boards/D007.txt
./bin/boardfolding < Boards/D008.txt
./bin/boardfolding < Boards/D009.txt
./bin/boardfolding < Boards/D010.txt
./bin/boardfolding < Boards/D011.txt
./bin/boardfolding < Boards/D012.txt
./bin/boardfolding < Boards/D013.txt
./bin/boardfolding < Boards/D014.txt
./bin/boardfolding < Boards/D015.txt
./bin/boardfolding < Boards/D016.txt
./bin/boardfolding < Boards/D017.txt
./bin/boardfolding < Boards/D018.txt
./bin/boardfolding < Boards/D019.txt
./bin/boardfolding < Boards/D020.txt
./bin/boardfolding < Boards/D021.txt
./bin/boardfolding < Boards/D022.txt
./bin/boardfolding < Boards/D023.txt
./bin/boardfolding < Boards/D024.txt
./bin/boardfolding < Boards/D025.txt
./bin/boardfolding < Boards/D026.txt
./bin/boardfolding < Boards/D027.txt
./bin/boardfolding < Boards/D028.txt
./bin/boardfolding < Boards/D029.txt
./bin/boardfolding < Boards/D030.txt
./bin/boardfolding < Boards/D031.txt
./bin/boardfolding < Boards/D032.txt
./bin/boardfolding < Boards/D033.txt
./bin/boardfolding < Boards/D034.txt
./bin/boardfolding < Boards/D035.txt
./bin/boardfolding < Boards/D036.txt
./bin/boardfolding < Boards/D037.txt
./bin/boardfolding < Boards/D038.txt
./bin/boardfolding < Boards/D039.txt
./bin/boardfolding < Boards/D040.txt
./bin/boardfolding < Boards/D041.txt
./bin/boardfolding < Boards/D042.txt
./bin/boardfolding < Boards/D043.txt
./bin/boardfolding < Boards/D044.txt
./bin/boardfolding < Boards/D045.txt
./bin/boardfolding < Boards/D046.txt
./bin/boardfolding < Boards/D047.txt
./bin/boardfolding < Boards/D048.txt
./bin/boardfolding < Boards/D049.txt
./bin/boardfolding < Boards/D050.txt
./bin/boardfolding < Boards/BF0.txt
./bin/boardfolding < Boards/BF1.txt
./bin/boardfolding < Boards/BF2.txt
./bin/boardfolding < Boards/BF3.txt
./bin/boardfolding < Boards/BF4.txt
./bin/boardfolding < Boards/BF5.txt
./bin/boardfolding < Boards/BF6.txt
./bin/boardfolding < Boards/BF7.txt
