#!/bin/sh 

dir=/home/jplank/cs302/Labs/Lab2

if [ $# -ne 1 ]; then
  echo 'usage: gradescript problem_number' >&2
  exit 1
fi

if [ "$1" -ge 0 ]; then
  enum=`echo $1 | awk '{ printf "%03d\n", $1 }'`
else
  echo 'usage: gradescript problem_number (>= 0)' >&2
  exit 1
fi
  
program=bin/lab_2
  
if [ ! -f $program ]; then
  echo "Problem $enum is incorrect."
  echo ""
  echo "Your program $program does not exist."
  exit 0
fi

rm -f tmp-$enum-test-stdout.txt tmp-$enum-test-stderr.txt tmp-$enum-correct-stdout.txt tmp-$enum-correct-stderr.txt

s=$(($1/3))
sel=$(($1%3))

echo $s $sel | $dir/$program > tmp-$enum-correct-stdout.txt 2> tmp-$enum-correct-stderr.txt
echo $s $sel | ./$program > tmp-$enum-test-stdout.txt 2> tmp-$enum-test-stderr.txt
call="echo $s $sel | ./$program"

out=`diff tmp-$enum-correct-stdout.txt tmp-$enum-test-stdout.txt | wc | awk '{ print $1 }'`
err=`diff tmp-$enum-correct-stderr.txt tmp-$enum-test-stderr.txt | wc | awk '{ print $1 }'`

if [ $out != 0 -o $err != 0 ]; then
  echo "Problem $enum is incorrect."
  echo ""
  if [ $out != 0 ]; then
    echo "Your standard output does not match the correct one."
  fi
  if [ $err != 0 ]; then
    echo "Your standard error does not match the correct one."
  fi
  echo ""
  echo "TEST:"
  echo ""
  echo "$call"
  echo ""
  echo "FILES:"
  echo ""
  echo "Your standard output is in tmp-$enum-test-stdout.txt."
  echo "Your standard error  is in tmp-$enum-test-stderr.txt."
  echo ""
  echo "The correct standard output is in tmp-$enum-correct-stdout.txt."
  echo "The correct standard error  is in tmp-$enum-correct-stderr.txt."
  echo ""
  echo "Look at correct files and your files, perhaps run 'diff -y' on them, and figure out your mistake."
  echo "Please remember to delete these files when you are finished."
else 
  echo "Problem $enum is correct."
  echo ""
  echo "Test:" 
  echo "$call" 
  rm -f tmp-$enum-test-stdout.txt tmp-$enum-test-stderr.txt tmp-$enum-correct-stdout.txt tmp-$enum-correct-stderr.txt
fi
