echo Boards/TC0.txt `sh -c 'time ./Board-Folding < Boards/TC0.txt' 2>&1`
echo Boards/TC1.txt `sh -c 'time ./Board-Folding < Boards/TC1.txt' 2>&1`
echo Boards/TC2.txt `sh -c 'time ./Board-Folding < Boards/TC2.txt' 2>&1`
echo Boards/TC3.txt `sh -c 'time ./Board-Folding < Boards/TC3.txt' 2>&1`
echo Boards/TC4.txt `sh -c 'time ./Board-Folding < Boards/TC4.txt' 2>&1`
echo Boards/D001.txt `sh -c 'time ./Board-Folding < Boards/D001.txt' 2>&1`
echo Boards/D002.txt `sh -c 'time ./Board-Folding < Boards/D002.txt' 2>&1`
echo Boards/D003.txt `sh -c 'time ./Board-Folding < Boards/D003.txt' 2>&1`
echo Boards/D004.txt `sh -c 'time ./Board-Folding < Boards/D004.txt' 2>&1`
echo Boards/D005.txt `sh -c 'time ./Board-Folding < Boards/D005.txt' 2>&1`
echo Boards/D006.txt `sh -c 'time ./Board-Folding < Boards/D006.txt' 2>&1`
echo Boards/D007.txt `sh -c 'time ./Board-Folding < Boards/D007.txt' 2>&1`
echo Boards/D008.txt `sh -c 'time ./Board-Folding < Boards/D008.txt' 2>&1`
echo Boards/D009.txt `sh -c 'time ./Board-Folding < Boards/D009.txt' 2>&1`
echo Boards/D010.txt `sh -c 'time ./Board-Folding < Boards/D010.txt' 2>&1`
echo Boards/D011.txt `sh -c 'time ./Board-Folding < Boards/D011.txt' 2>&1`
echo Boards/D012.txt `sh -c 'time ./Board-Folding < Boards/D012.txt' 2>&1`
echo Boards/D013.txt `sh -c 'time ./Board-Folding < Boards/D013.txt' 2>&1`
echo Boards/D014.txt `sh -c 'time ./Board-Folding < Boards/D014.txt' 2>&1`
echo Boards/D015.txt `sh -c 'time ./Board-Folding < Boards/D015.txt' 2>&1`
echo Boards/D016.txt `sh -c 'time ./Board-Folding < Boards/D016.txt' 2>&1`
echo Boards/D017.txt `sh -c 'time ./Board-Folding < Boards/D017.txt' 2>&1`
echo Boards/D018.txt `sh -c 'time ./Board-Folding < Boards/D018.txt' 2>&1`
echo Boards/D019.txt `sh -c 'time ./Board-Folding < Boards/D019.txt' 2>&1`
echo Boards/D020.txt `sh -c 'time ./Board-Folding < Boards/D020.txt' 2>&1`
echo Boards/D021.txt `sh -c 'time ./Board-Folding < Boards/D021.txt' 2>&1`
echo Boards/D022.txt `sh -c 'time ./Board-Folding < Boards/D022.txt' 2>&1`
echo Boards/D023.txt `sh -c 'time ./Board-Folding < Boards/D023.txt' 2>&1`
echo Boards/D024.txt `sh -c 'time ./Board-Folding < Boards/D024.txt' 2>&1`
echo Boards/D025.txt `sh -c 'time ./Board-Folding < Boards/D025.txt' 2>&1`
echo Boards/D026.txt `sh -c 'time ./Board-Folding < Boards/D026.txt' 2>&1`
echo Boards/D027.txt `sh -c 'time ./Board-Folding < Boards/D027.txt' 2>&1`
echo Boards/D028.txt `sh -c 'time ./Board-Folding < Boards/D028.txt' 2>&1`
echo Boards/D029.txt `sh -c 'time ./Board-Folding < Boards/D029.txt' 2>&1`
echo Boards/D030.txt `sh -c 'time ./Board-Folding < Boards/D030.txt' 2>&1`
echo Boards/D031.txt `sh -c 'time ./Board-Folding < Boards/D031.txt' 2>&1`
echo Boards/D032.txt `sh -c 'time ./Board-Folding < Boards/D032.txt' 2>&1`
echo Boards/D033.txt `sh -c 'time ./Board-Folding < Boards/D033.txt' 2>&1`
echo Boards/D034.txt `sh -c 'time ./Board-Folding < Boards/D034.txt' 2>&1`
echo Boards/D035.txt `sh -c 'time ./Board-Folding < Boards/D035.txt' 2>&1`
echo Boards/D036.txt `sh -c 'time ./Board-Folding < Boards/D036.txt' 2>&1`
echo Boards/D037.txt `sh -c 'time ./Board-Folding < Boards/D037.txt' 2>&1`
echo Boards/D038.txt `sh -c 'time ./Board-Folding < Boards/D038.txt' 2>&1`
echo Boards/D039.txt `sh -c 'time ./Board-Folding < Boards/D039.txt' 2>&1`
echo Boards/D040.txt `sh -c 'time ./Board-Folding < Boards/D040.txt' 2>&1`
echo Boards/D041.txt `sh -c 'time ./Board-Folding < Boards/D041.txt' 2>&1`
echo Boards/D042.txt `sh -c 'time ./Board-Folding < Boards/D042.txt' 2>&1`
echo Boards/D043.txt `sh -c 'time ./Board-Folding < Boards/D043.txt' 2>&1`
echo Boards/D044.txt `sh -c 'time ./Board-Folding < Boards/D044.txt' 2>&1`
echo Boards/D045.txt `sh -c 'time ./Board-Folding < Boards/D045.txt' 2>&1`
echo Boards/D046.txt `sh -c 'time ./Board-Folding < Boards/D046.txt' 2>&1`
echo Boards/D047.txt `sh -c 'time ./Board-Folding < Boards/D047.txt' 2>&1`
echo Boards/D048.txt `sh -c 'time ./Board-Folding < Boards/D048.txt' 2>&1`
echo Boards/D049.txt `sh -c 'time ./Board-Folding < Boards/D049.txt' 2>&1`
echo Boards/D050.txt `sh -c 'time ./Board-Folding < Boards/D050.txt' 2>&1`
echo Boards/BF0.txt `sh -c 'time ./Board-Folding < Boards/BF0.txt' 2>&1`
echo Boards/BF1.txt `sh -c 'time ./Board-Folding < Boards/BF1.txt' 2>&1`
echo Boards/BF2.txt `sh -c 'time ./Board-Folding < Boards/BF2.txt' 2>&1`
echo Boards/BF3.txt `sh -c 'time ./Board-Folding < Boards/BF3.txt' 2>&1`
echo Boards/BF4.txt `sh -c 'time ./Board-Folding < Boards/BF4.txt' 2>&1`
echo Boards/BF5.txt `sh -c 'time ./Board-Folding < Boards/BF5.txt' 2>&1`
echo Boards/BF6.txt `sh -c 'time ./Board-Folding < Boards/BF6.txt' 2>&1`
echo Boards/BF7.txt `sh -c 'time ./Board-Folding < Boards/BF7.txt' 2>&1`
